API_KEY: 
output_folder: data
channel_ids:
  - UC-lHJZR3Gqxm24_Vd_AJ5Yw # PewDiePie
  - UC7_YxT-KID8kRbqZo7MyscQ # Markiplier
  - UCpB959t8iPrxQWj7G6n0ctQ # SSSniperWolf
  - UCAW-NpUFkMyCNrvRSSGIvDQ # Ninja
  - UC-kOXc3gBwksVfmndSEz7jg # WILDCAT
  - UCrPseYLGpNygVi34QpGNqpA # Ludwig
  - UC0VVYtw21rg2cokUystu2Dw # SmallAnt
  - UC3tNpTOHsTnkmbwztCs30sA # Northernlion
  - UCTkXRDQl0luXxVQrRQvWS6w # Dream
  - UCYzPXprvl5Y-Sf0g4vX-m6g # jacksepticeye
  - UCS5Oz6CHmeoF7vSad0qqXfw # DanTDM
  - UCMdGPato0IC5-zZjJIf-P9w # SwaggerSouls
  - UCq6VFHwMzcMXbuKyG7SQYIg # penguinz0
  - UCDvm7YoLE5r3ZZ6MWyD2vGQ # NICKMERCS
  - UCUT8RoNBTJvwW1iErP6-b-A # Disguised Toast
  - UCP9tAErY_RlX4RFKssE4ogg # NoahJ456
  - UCIPPMRA040LQr5QPyJEbmXA # MrBeast Gaming
  - UCIIPl-DSCC0prKxGGnJrdGQ # Austin John Plays
  - UCcJL2ld6kxy_nuV1u7PVQ0g # DrDisRespect
  - UC2mP7il3YV7TxM_3m6U0bwA # jschlattLIVE
  - UChl76B7zqfMcNzfMi9vJruw # Mizkif
  - UCYsGgfAcQ91Fpda3_O-h0LA # Clint Stevens
  - UCvjsnl6wNtVIm0i1sCpN9Uw # Pokemon Challenges
  - UCzXwjTI6c6mVn6oui_p6oiw # SMii7Y
  - UC7trU46U_9XPDtMnDbiDPUQ # FaZe Jev
  - UCKqH_9mk1waLgBiL2vT5b9g # VanossGaming
  - UCw1SQ6QRRtfAhrN_cjkrOgA # LazarBeam
